#!/usr/bin/with-contenv sh

if [ "$CF_DNS__LOG_TYPE" == "json" ]; then
  msg='{"level":30,"time":';
  msg+=$(date +%s%3N)
  msg+=',"pid":';
  msg+="$$";
  msg+=',"hostname":"';
  msg+=$(hostname);
  msg+='","msg":"Initializing container"}'
  echo "$msg";
else
  echo "
  Initializing container

  User uid: $(id -u node)
  User gid: $(id -g node)
";
fi


chown node:node /app
